config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def edit
    @list = List.find(params[:id])
    render :form
  end

  def create
    @list = List.new(page_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :form
    end
  end

  def update
    @list = List.find(params[:id])

    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :form
    end
  end

  def destroy
    List.find(params[:id]).destroy
    redirect_to lists_path
  end

  private
    def list_params
      lists.require(:page).permit(:what, :where, :when)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Lists', lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODOList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/form.html.erb
<h1>
  <%= @list.id ? 'Revise List' : 'Add List' %>
</h1>
<%= form_for @list do |f| %>
  <fieldset>
    <legend>List Info</legend>
    <%= f.label :what %>
    <%= f.text_field :what %>
    <br />
    <br />
    <%= f.label :when %>
    <%= f.text_field :when %>
    <br />
    <br />
    <%= f.label :where %>
    <%= f.text_field :where %>
    <br />
    <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<h1> Lists </h1>
<p>
  <%= link_to 'New List', new_list_path %>
</p>
<% @lists.each do |list| %>
  <h2><%= list.title %></h2>
  <%= link_to 'Visit', list_path(list) %>
<% end %>

app/views/lists/new.html.erb
<h1>
  <%= @list.id ? 'Revise List' : 'Add List' %>
</h1>
<%= form_for @list do |f| %>
  <fieldset>
    <legend>List Info</legend>
    <%= f.label :what %>
    <%= f.text_field :what %>
    <br />
    <br />
    <%= f.label :when %>
    <%= f.text_field :when %>
    <br />
    <br />
    <%= f.label :where %>
    <%= f.text_field :where %>
    <br />
    <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.what %></h1>
<h3><%= @list.when %></h3>
<h3><%= @list.where %></h3>
<hr />
<%= link_to 'Revise List', revise_list_path(@list) %>
<%= link_to 'Destroy List', @list, method: :delete %>
<%= link_to 'Back', lists_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>